export var apiConfig = {
    baseUrl: "https://picsum.photos/400/400"    //https://picsum.photos/200/300?random={int}
}

export var defaultAnnouncement = "In the future, you can rank your challenge result with other people.";

var baseUrl = "challenges/";
var baseUrl = "static/matchandgo/challenges/"   //python

export var challengeMapping = {
    1: {
        rows: 2,
        columns: 7,
        images: [
            baseUrl+"challenge1/tile1.jpg",
            baseUrl+"challenge1/tile2.jpg",
            baseUrl+"challenge1/tile3.jpg",
            baseUrl+"challenge1/tile4.jpg",
            baseUrl+"challenge1/tile5.jpg",
            baseUrl+"challenge1/tile6.jpg",
            baseUrl+"challenge1/tile7.jpg",
        ]
    },
    2: {
        rows: 4,
        columns: 8,
        images: [
            baseUrl+"challenge2/tile1-min.jpg",
            baseUrl+"challenge2/tile2-min.jpg",
            baseUrl+"challenge2/tile3-min.jpg",
            baseUrl+"challenge2/tile4-min.jpg",
            baseUrl+"challenge2/tile5-min.jpg",
            baseUrl+"challenge2/tile6-min.jpg",
            baseUrl+"challenge2/tile7-min.jpg",
            baseUrl+"challenge2/tile8-min.jpg",
            baseUrl+"challenge2/tile9-min.jpg",
            baseUrl+"challenge2/tile10-min.jpg",
            baseUrl+"challenge2/tile11-min.jpg",
            baseUrl+"challenge2/tile12-min.jpg",
            baseUrl+"challenge2/tile13-min.jpg",
            baseUrl+"challenge2/tile14-min.jpg",
            baseUrl+"challenge2/tile15-min.jpg",
            baseUrl+"challenge2/tile16-min.jpg",
        ]
    },
    3: {
        rows: 8,
        columns: 8,
        images: [
            baseUrl+"challenge3/1-min.jpg",
            baseUrl+"challenge3/2-min.jpg",
            baseUrl+"challenge3/3-min.jpg",
            baseUrl+"challenge3/4-min.jpg",
            baseUrl+"challenge3/5-min.jpg",
            baseUrl+"challenge3/6-min.jpg",
            baseUrl+"challenge3/7-min.jpg",
            baseUrl+"challenge3/8-min.jpg",
            baseUrl+"challenge3/9-min.jpg",
            baseUrl+"challenge3/10-min.jpg",
            baseUrl+"challenge3/11-min.jpg",
            baseUrl+"challenge3/12-min.jpg",
            baseUrl+"challenge3/13-min.jpg",
            baseUrl+"challenge3/14-min.jpg",
            baseUrl+"challenge3/15-min.jpg",
            baseUrl+"challenge3/16-min.jpg",
            baseUrl+"challenge3/17-min.jpg",
            baseUrl+"challenge3/18-min.jpg",
            baseUrl+"challenge3/19-min.jpg",
            baseUrl+"challenge3/20-min.jpg",
            baseUrl+"challenge3/21-min.jpg",
            baseUrl+"challenge3/22-min.jpg",
            baseUrl+"challenge3/23-min.jpg",
            baseUrl+"challenge3/24-min.jpg",
            baseUrl+"challenge3/25-min.jpg",
            baseUrl+"challenge3/26-min.jpg",
            baseUrl+"challenge3/27-min.jpg",
            baseUrl+"challenge3/28-min.jpg",
            baseUrl+"challenge3/29-min.jpg",
            baseUrl+"challenge3/30-min.jpg",
            baseUrl+"challenge3/31-min.jpg",
            baseUrl+"challenge3/32-min.jpg",
        ]
    },
    4: {
        rows: 8,
        columns: 8,
        images: [
            baseUrl+"challenge4/1-min.jpg",
            baseUrl+"challenge4/2-min.jpg",
            baseUrl+"challenge4/3-min.jpg",
            baseUrl+"challenge4/4-min.jpg",
            baseUrl+"challenge4/5-min.jpg",
            baseUrl+"challenge4/6-min.jpg",
            baseUrl+"challenge4/7-min.jpg",
            baseUrl+"challenge4/8-min.jpg",
            baseUrl+"challenge4/9-min.jpg",
            baseUrl+"challenge4/10-min.jpg",
            baseUrl+"challenge4/11-min.jpg",
            baseUrl+"challenge4/12-min.jpg",
            baseUrl+"challenge4/13-min.jpg",
            baseUrl+"challenge4/14-min.jpg",
            baseUrl+"challenge4/15-min.jpg",
            baseUrl+"challenge4/16-min.jpg",
            baseUrl+"challenge4/17-min.jpg",
            baseUrl+"challenge4/18-min.jpg",
            baseUrl+"challenge4/19-min.jpg",
            baseUrl+"challenge4/20-min.jpg",
            baseUrl+"challenge4/21-min.jpg",
            baseUrl+"challenge4/22-min.jpg",
            baseUrl+"challenge4/23-min.jpg",
            baseUrl+"challenge4/24-min.jpg",
            baseUrl+"challenge4/25-min.jpg",
            baseUrl+"challenge4/26-min.jpg",
            baseUrl+"challenge4/27-min.jpg",
            baseUrl+"challenge4/28-min.jpg",
            baseUrl+"challenge4/29-min.jpg",
            baseUrl+"challenge4/30-min.jpg",
            baseUrl+"challenge4/31-min.jpg",
            baseUrl+"challenge4/32-min.jpg",
        ]
    },
    5: {
        rows: 8,
        columns: 8,
        images: [
            baseUrl+"challenge5/1-min.jpg",
            baseUrl+"challenge5/2-min.jpg",
            baseUrl+"challenge5/3-min.jpg",
            baseUrl+"challenge5/4-min.jpg",
            baseUrl+"challenge5/5-min.jpg",
            baseUrl+"challenge5/6-min.jpg",
            baseUrl+"challenge5/7-min.jpg",
            baseUrl+"challenge5/8-min.jpg",
            baseUrl+"challenge5/9-min.jpg",
            baseUrl+"challenge5/10-min.jpg",
            baseUrl+"challenge5/11-min.jpg",
            baseUrl+"challenge5/12-min.jpg",
            baseUrl+"challenge5/13-min.jpg",
            baseUrl+"challenge5/14-min.jpg",
            baseUrl+"challenge5/15-min.jpg",
            baseUrl+"challenge5/16-min.jpg",
            baseUrl+"challenge5/17-min.jpg",
            baseUrl+"challenge5/18-min.jpg",
            baseUrl+"challenge5/19-min.jpg",
            baseUrl+"challenge5/20-min.jpg",
            baseUrl+"challenge5/21-min.jpg",
            baseUrl+"challenge5/22-min.jpg",
            baseUrl+"challenge5/23-min.jpg",
            baseUrl+"challenge5/24-min.jpg",
            baseUrl+"challenge5/25-min.jpg",
            baseUrl+"challenge5/26-min.jpg",
            baseUrl+"challenge5/27-min.jpg",
            baseUrl+"challenge5/28-min.jpg",
            baseUrl+"challenge5/29-min.jpg",
            baseUrl+"challenge5/30-min.jpg",
            baseUrl+"challenge5/31-min.jpg",
            baseUrl+"challenge5/32-min.jpg",
        ]
    },
    6: {
        rows: 8,
        columns: 8,
        images: [
            baseUrl+"challenge6/1-min.jpg",
            baseUrl+"challenge6/2-min.jpg",
            baseUrl+"challenge6/3-min.jpg",
            baseUrl+"challenge6/4-min.jpg",
            baseUrl+"challenge6/5-min.jpg",
            baseUrl+"challenge6/6-min.jpg",
            baseUrl+"challenge6/7-min.jpg",
            baseUrl+"challenge6/8-min.jpg",
            baseUrl+"challenge6/9-min.jpg",
            baseUrl+"challenge6/10-min.jpg",
            baseUrl+"challenge6/11-min.jpg",
            baseUrl+"challenge6/12-min.jpg",
            baseUrl+"challenge6/13-min.jpg",
            baseUrl+"challenge6/14-min.jpg",
            baseUrl+"challenge6/15-min.jpg",
            baseUrl+"challenge6/16-min.jpg",
            baseUrl+"challenge6/17-min.jpg",
            baseUrl+"challenge6/18-min.jpg",
            baseUrl+"challenge6/19-min.jpg",
            baseUrl+"challenge6/20-min.jpg",
            baseUrl+"challenge6/21-min.jpg",
            baseUrl+"challenge6/22-min.jpg",
            baseUrl+"challenge6/23-min.jpg",
            baseUrl+"challenge6/24-min.jpg",
            baseUrl+"challenge6/25-min.jpg",
            baseUrl+"challenge6/26-min.jpg",
            baseUrl+"challenge6/27-min.jpg",
            baseUrl+"challenge6/28-min.jpg",
            baseUrl+"challenge6/29-min.jpg",
            baseUrl+"challenge6/30-min.jpg",
            baseUrl+"challenge6/31-min.jpg",
            baseUrl+"challenge6/32-min.jpg",
        ]
    },
}